# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Zhi-Xiang Yu
    url: /
    weight: 10
  - name: Members
    url: /Members/
    weight: 20
  - name: Research
    url: /Research/
    weight: 30
  # - name: Experience
  #   url: /experience
  #   weight: 40
  - name: Publications
    url: /publications
    weight: 50